server.port=${PORT:8080}

# Nome do banco
spring.application.name=adieljulia-api

# Conexão com o Banco de Dados separada
spring.datasource.url=jdbc:postgresql://ep-wild-violet-a4q2wpaj.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oyhA6BFb4YDw
spring.datasource.driver-class-name=org.postgresql.Driver

# Para o Spring criar a tabela de convidados automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect